# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
path_classifiers:
  test:
    - "*/test/**/*"
extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
      script:
        - python3 -m pip install cmake
        - source ~/.profile
    configure:
      command:
        - mkdir build
        - cmake -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build
    index:
      build_command: cmake --build ./build -- -j2
